/**
 * Keeps the public membership number stable even for records generated by the
 * legacy database function, which appended the year twice.
 */
export function normalizeMembershipNumber(value: string | null | undefined): string {
  // IDs are copied from certificates and older spreadsheets, where accidental
  // spaces are common. They are never meaningful inside a member ID.
  const raw = value?.trim().replace(/\s+/g, "");
  if (!raw) return "";

  // Legacy value: DKFFJ/M/2026/-2026-00031
  // Official value: DKFFJ/M/2026/00031
  const legacyMatch = raw.match(/^DKFFJ\/M\/(\d{4})\/(?:-?\d{4}-)?(\d+)$/i);
  if (!legacyMatch) return raw;

  const [, year, sequence] = legacyMatch;
  return `DKFFJ/M/${year}/${sequence.padStart(5, "0")}`;
}

/**
 * New membership records use DKFFJ/M/YYYY/00000.  Records migrated from the
 * Executive Council registry legitimately use DKFFJ/EXEC/YYYY/<serial> and
 * must remain editable and printable forever.  Do not convert EXEC IDs to M.
 */
export function isRecognizedMembershipNumber(value: string | null | undefined): boolean {
  const normalized = normalizeMembershipNumber(value);
  return /^DKFFJ\/M\/\d{4}\/\d{5,}$/i.test(normalized)
    || /^DKFFJ\/EXEC\/\d{4}\/\d+$/i.test(normalized);
}

export function toLegacyMembershipNumber(value: string | null | undefined): string {
  const normalized = normalizeMembershipNumber(value);
  const match = normalized.match(/^DKFFJ\/M\/(\d{4})\/(\d+)$/i);
  if (!match) return normalized;

  const [, year, sequence] = match;
  return `DKFFJ/M/${year}/-${year}-${sequence}`;
}

export function normalizeCourseEnrollmentNumber(value: string | null | undefined): string {
  const raw = value?.trim();
  if (!raw) return "";

  // Legacy value: DKFFJ/C/2026/-2026-00021
  // Official value: DKFFJ/C/2026/00021
  const legacyMatch = raw.match(/^DKFFJ\/C\/(\d{4})\/(?:-?\d{4}-)?(\d+)$/i);
  if (!legacyMatch) return raw;

  const [, year, sequence] = legacyMatch;
  return `DKFFJ/C/${year}/${sequence.padStart(5, "0")}`;
}
