/**
 * Keeps the public membership number stable even for records generated by the
 * legacy database function, which appended the year twice.
 */
export function normalizeMembershipNumber(value: string | null | undefined): string {
  const raw = value?.trim();
  if (!raw) return "";

  // Legacy value: DKFFJ/M/2026/-2026-00031
  // Official value: DKFFJ/M/2026/00031
  const legacyMatch = raw.match(/^DKFFJ\/M\/(\d{4})\/(?:-?\d{4}-)?(\d+)$/i);
  if (!legacyMatch) return raw;

  const [, year, sequence] = legacyMatch;
  return `DKFFJ/M/${year}/${sequence.padStart(5, "0")}`;
}

export function toLegacyMembershipNumber(value: string | null | undefined): string {
  const normalized = normalizeMembershipNumber(value);
  const match = normalized.match(/^DKFFJ\/M\/(\d{4})\/(\d+)$/i);
  if (!match) return normalized;

  const [, year, sequence] = match;
  return `DKFFJ/M/${year}/-${year}-${sequence}`;
}
